// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCzpt-_FbFXZHYLb8ZQ3bf2vVwZEbQ3i0',
    appId: '1:646489324251:web:4249413e0b82fc07ee6afe',
    messagingSenderId: '646489324251',
    projectId: 'projetanilist',
    authDomain: 'projetanilist.firebaseapp.com',
    databaseURL: 'https://projetanilist-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetanilist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvjRt6CR9Vf_C_pYmM3z8s_XvOSnnnwo',
    appId: '1:646489324251:android:1604c1576ed6a7daee6afe',
    messagingSenderId: '646489324251',
    projectId: 'projetanilist',
    databaseURL: 'https://projetanilist-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetanilist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-h7D88LLORDJUfxaXhFYdNmGtFHNJWLA',
    appId: '1:646489324251:ios:3aef1b1f15ef2978ee6afe',
    messagingSenderId: '646489324251',
    projectId: 'projetanilist',
    databaseURL: 'https://projetanilist-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetanilist.appspot.com',
    iosClientId: '646489324251-aes9oevo1a326pm7d723m464d7n5m4v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.anilist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-h7D88LLORDJUfxaXhFYdNmGtFHNJWLA',
    appId: '1:646489324251:ios:3aef1b1f15ef2978ee6afe',
    messagingSenderId: '646489324251',
    projectId: 'projetanilist',
    databaseURL: 'https://projetanilist-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projetanilist.appspot.com',
    iosClientId: '646489324251-aes9oevo1a326pm7d723m464d7n5m4v8.apps.googleusercontent.com',
    iosBundleId: 'com.example.anilist',
  );
}
